// Get a list of resources that support publicNetworkAccess
// The list of resources that support publicNetworkAccess is generated by the script generate_pna.py    
// The list of resources that support publicNetworkAccess is stored in the file pna_resources.json
// The list of resources that support publicNetworkAccess is used to create a policy definition in Azure for each resource type that supports publicNetworkAccess.
// The policy definition is created by the script create_pna_policy_definitions.sh
// The script create_pna_policy_definitions.sh uses the Azure CLI to create a policy definition in Azure for each resource type that supports publicNetworkAccess.
// The script create_pna_policy_definitions.sh uses the file pna_resources.json to get the list of resources that support publicNetworkAccess.
// The script create_pna_policy_definitions.sh uses the file pna_template_policy.json as a template to create the policy definition in Azure.
// The script create_pna_policy_definitions.sh uses the file pna_template_policy.json to create a policy definition in Azure for each resource type that supports publicNetworkAccess.
//
// Usage: python generate_pna_ver1.py
//
// Example:  python generate_pna_ver1.py  > pna_resources.json
//
// Note: This script requires the Azure CLI to be installed and logged in to an Azure subscription.
//
az login
// Get list of all resource types
resource_types=$(az provider list --query [].namespace --output tsv)
// Loop through each resource type and get publicNetworkAccess property
for resource_type in $resource_types
do
    public_network_access=$(az provider show --namespace $resource_type --query "resourceTypes[?resourceType=='*'].properties.publicNetworkAccess" --output tsv)
    // If publicNetworkAccess property is not null, then add resource type to list of resources that support publicNetworkAccess
    if [ "$public_network_access" != "None" ]
    then
        echo $resource_type
    fi
done
// Create policy definition in Azure for each resource type that supports publicNetworkAccess
// Get list of resource types that support publicNetworkAccess
resource_types=$(cat pna_resources.json | jq -r '.[]')
// 
